apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
    - name: resource
      image: centos
      command: ["/bin/bash", "-c", "while true; do echo Grras Training; sleep 5 ; done"]
      resources:
        limits:
          cpu: "1"
